# Generated by Django 4.2.16 on 2024-11-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyWrappedApp', '0002_user_created_at_solowraps'),
    ]

    operations = [
        migrations.AddField(
            model_name='solowraps',
            name='unique_id',
            field=models.CharField(default='<function uuid4 at 0x103e0aca0>', editable=False, max_length=36, unique=True),
        ),
    ]
