# Generated by Django 4.2.16 on 2024-11-17 21:22

import SpotifyWrappedApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyWrappedApp', '0003_solowraps_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solowraps',
            name='unique_id',
            field=models.CharField(default=SpotifyWrappedApp.models.generate_unique_id, editable=False, max_length=36, unique=True),
        ),
    ]
