# Generated by Django 4.2.16 on 2024-12-02 02:59

import SpotifyWrappedApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyWrappedApp', '0004_alter_solowraps_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuoWraps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=SpotifyWrappedApp.models.generate_unique_id, editable=False, max_length=36, unique=True)),
                ('wrap_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duo_wraps_1', to='SpotifyWrappedApp.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duo_wraps_2', to='SpotifyWrappedApp.user')),
            ],
        ),
    ]
